core/urls.py
import debug_toolbar

from django.conf import settings
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path

# from schemas.views import home

from schemas.views import SchemasListView


urlpatterns = [
    path('', login_required(SchemasListView.as_view(), login_url='/users/u_login'), name='home'),
    path('__debug__/', include(debug_toolbar.urls)),
    # path('', home, name='home'),
    path('schemas/', include('schemas.urls')),
    path('data_gen/', include('data_gen.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('u_auth.urls')),
]

schemas/urls.py
from django.contrib import admin
from django.urls import include, path

from schemas import views

urlpatterns = [
    path('create', views.create_schema, name='new_schema'),
    path('update/<int:pk>', views.update_schema, name='upd_schema'),
    path('detail/<int:pk>', views.detail_schema, name='detail_schema'),
    path('delete_cls_bsd/<int:pk>', views.SchemaDeleteView.as_view(), name='dlt_schema'),
]

data_gen/models.py
from django.db import models

from schemas.models import Schema


class DataSetFile(models.Model):
    ready = 'RD'
    processing = 'PR'

    status_choices = [
        (ready, 'Ready'),
        (processing, 'Processing')
    ]

    created = models.DateField(auto_now=True)
    status = models.CharField(max_length=2, choices=status_choices, default=processing)
    url = models.URLField(max_length=200, default='static/media/default.csv')
    schema = models.ForeignKey(Schema, on_delete=models.CASCADE)

    def __str__(self):
        return 'file'

schemas/models.py
from django.db import models


class Schema(models.Model):
    coma = ','
    semicolon = ';'

    sep_choices = [
        (coma, 'Coma'),
        (semicolon, 'Semicolon'),
    ]

    quotes_o = "'"
    quotes_d = '"'

    string_character_choices = [
        (quotes_o, 'Single quotes'),
        (quotes_d, 'Double quotes'),
    ]

    name = models.CharField(max_length=100, blank=False, unique=True)
    separator = models.CharField(
        max_length=1,
        choices=sep_choices,
        default=coma,
    )
    string_character = models.CharField(
        max_length=1,
        choices=string_character_choices,
        default=quotes_o,
    )
    modified = models.DateField(auto_now=True)

    def __str__(self):
        return self.name


class Column(models.Model):
    undefined = 'UD'
    full_name = 'FN'
    job = 'JB'
    email = 'EM'
    domain_name = 'DN'
    phone_number = 'PN'
    company_name = 'CN'

    type_choices = [
        (undefined, 'Undefined'),
        (full_name, 'Full Name'),
        (job, 'Job'),
        (email, 'Email'),
        (domain_name, 'Domain name'),
        (phone_number, 'Phone number'),
        (company_name, 'Company name'),
    ]

    name = models.CharField(max_length=100, blank=False)
    field_type = models.CharField(
        max_length=2,
        choices=type_choices,
        default=undefined,
    )
    order = models.PositiveSmallIntegerField(default=0)
    schema = models.ForeignKey(Schema, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

schemas/forms.py
from django import forms

from . import models


class SchemaModelForm(forms.ModelForm):
    class Meta:
        model = models.Schema
        fields = ['name', 'separator', 'string_character']


class ColumnModelForm(forms.ModelForm):
    class Meta:
        model = models.Column
        fields = ['name', 'field_type', 'order', 'schema']

schemas/views.py
from data_gen.forms import AmountForm

from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import DeleteView, ListView

from schemas.tasks import data_gen_new

from .forms import SchemaModelForm
from .models import Column, Schema


class SchemasListView(ListView):
    model = Schema
    template_name = 'schemas/home_data_schemas.html'
    fields = ['name', 'separator', 'string_character', 'column']


@login_required(login_url='/users/u_login')
def detail_schema(request, pk):
    if request.method == 'POST':
        form = AmountForm(request.POST)
        if form.is_valid():
            amount = form.cleaned_data['data_gen_amount']
            data_gen_new(pk, amount)
            schema = Schema.objects.get(id=pk)
            context = {'schema': schema, 'form': form}
            # messages.success(request, ('Данные генерируются'))
            return HttpResponseRedirect(reverse('detail_schema', kwargs={'pk': pk}))
            # return render(request, 'schemas/schema_data_sets.html', context)
    form = AmountForm()
    schema = Schema.objects.get(id=pk)
    context = {'schema': schema, 'form': form}
    return render(request, 'schemas/schema_data_sets.html', context)


def create_schema(request):
    scheme_form_set = inlineformset_factory(Schema, Column,
                                            fields=('name', 'field_type', 'order'), extra=1)
    if request.method == 'POST':
        form = SchemaModelForm(request.POST)  # первичное создание объекта при нажатии на  ADD
        if form.is_valid():
            name = form.cleaned_data['name']
            form.save()
            instance = Schema.objects.get(name=name)
            pk = instance.pk
            formset = scheme_form_set(request.POST, request.FILES, instance=instance)
            if formset.is_valid():
                formset.save()
                if request.POST.get('save_schema'):
                    return HttpResponseRedirect(reverse('home'))
                if request.POST.get('add_column'):
                    return HttpResponseRedirect(reverse('upd_schema', args=[pk]))
    form = SchemaModelForm()  # первый случай загрузки формы при нажатии на ссылку
    formset = scheme_form_set()
    context = {'formset': formset, 'form': form}
    return render(request, 'schemas/new_schema.html', context)


def update_schema(request, pk):
    scheme_form_set = inlineformset_factory(Schema, Column,
                                            fields=('name', 'field_type', 'order'), extra=1)
    if request.method == 'POST':
        instance = Schema.objects.get(id=pk)
        form = SchemaModelForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            formset = scheme_form_set(request.POST, request.FILES, instance=instance)
            if formset.is_valid():
                formset.save()
                if 'save_schema' in request.POST:
                    return HttpResponseRedirect(reverse('home'))
    instance = Schema.objects.get(id=pk)
    formset = scheme_form_set(instance=instance)
    form = SchemaModelForm(instance=instance)
    context = {'formset': formset, 'form': form}
    return render(request, 'schemas/new_schema.html', context)


class SchemaDeleteView(DeleteView):
    model = Schema
    pk_url_kwarg = 'pk'
    template_name = 'schemas/del_obj.html'
    success_url = '/'


@login_required(login_url='/users/u_login')
def new_schema(request):
    return render(request, 'schemas/new_schema.html')

templates/schemas/del_obj.html
{% extends 'base.html' %}
{% load static %}

{% block title%}Deletion{% endblock %}

{% block content%}

{% csrf_token %}
<form method="post">
  {% csrf_token %}
    <p>Delete {{ object.name}} ?</p>
  <input type="submit" value="Submit">
</form>
{% endblock %}

templates/schemas/home_data_schemas.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}

<!--кнопка и форма с кол-вом-->
<div class="container">
  <div class="row">
    <h2>Data Schemas</h2>
    <div class="col-lg-1"></div>
    <div class="col-lg-2">
      <form action="{% url 'new_schema' %}" method="get">
        <button class="btn btn-success">New Schema</button>
      </form>
    </div>
  </div>
</div>
<!--конец кнопки-->

<!--основная таблица Тут будет цикл-->
<div class="container">
  <div class="row row-cols-auto">
    <div class="col-lg-1">№</div>
    <div class="col-lg-5">Title</div>
    <div class="col-lg-3">Modified</div>
    <div class="col-lg-3">Actions</div>
  </div>
  {% for instance in object_list %}
  <div class="row row-cols-auto">
    <div class="col-lg-1">{{ instance.id }}</div>

    <div class="col-lg-5"><a href="{% url 'detail_schema' instance.id %}">{{ instance.name }}</a> data sets</div>
    <div class="col-lg-3">{{ instance.modified }}</div>
    <div class="col-lg-3">
      <a href="{% url 'upd_schema' instance.id %}">Edit</a>
      <a href="{% url 'dlt_schema' instance.id %}">Delete</a>
    </div>
  </div>
  {% endfor %}
</div>
<!--конец основной таблицы-->

{% endblock %}

templates/schemas/new_schema.html
{% extends 'base.html' %}
{% load static %}

{% block title %}New Schema{% endblock %}

{% block content %}

<h2>New Schema</h2>
<!--форма схемы-->
<form method="post">
  {% csrf_token %}

  {% for field in form %}
  <p>{{ field.label }} {{ field }}</p>
  {% endfor %}

  <button type="submit" name="save_schema" value="Save" class="btn btn-primary">Submit</button>

  <h2>Schema columns</h2>

    {{ formset.management_form }}
  {% for field in formset %}
  <p>{{ field.label }} {{ field }}</p>
  {% endfor %}

    <button type="submit" name="add_column" value="Add" class="btn btn-primary">Add column</button>

</form>

<!--конец формы схемы-->

{% endblock %}

templates/schemas/schema_data_sets.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ schema.name }} data sets{% endblock %}

{% block content %}

<!--кнопка и форма с кол-вом-->
<div class="container">
  <div class="row">
    <h2>{{ schema.name }} Data Sets</h2>
    <div class="col-lg-6"></div>
    <div class="col-lg-4">
      <form action="{% url 'detail_schema' schema.id %}" method="post">
        {% csrf_token %}
        {{ form }}
    </div>
    <div class="col-lg-2"><button class="btn btn-success">Generate data</button></div>
    </form>
  </div>
</div>
<!--конец кнопки-->

<!--основная таблица Тут будет цикл-->
<div class="container">
  <div class="row">
    <div class="col-lg-2">#</div>
    <div class="col-lg-2">Created</div>
    <div class="col-lg-3">Status</div>
    <div class="col-lg-3">Actions</div>
  </div>
  {% for file in schema.datasetfile_set.all %}
  <div class="row">
    <div class="col-lg-2">{{ file.id }}</div>
    <div class="col-lg-2">{{ file.created }}</div>
    <div class="col-lg-3">{{ file.status }}</div>
    <div class="col-lg-3"><a href="../../{{ file.url }}" download>Download</a></div>
  </div>
  {% endfor %}

</div>
<!--конец основной таблицы-->

{% endblock %}